config/routes.rb
Rails.application.routes.draw do

  get 'likes/created'

  get '/menu' => 'posts#menu'
  get '/menu/:id' => 'posts#show1' 
  get '/posts/:id/like'=>'likes#dar_like'
  resources :posts
  resources :comments
  resources :likes

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/like.rb
class Like < ActiveRecord::Base
belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@post=Post.find(params[:post_id])
  	@comment=@post.comments.build(params[:text])
  	@comment.save

  	redirect_to @post
  end

  def show
  end

private
  def comment_params
    params.require(:comment).permit(:text, :post_id)
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def dar_like
  	@like=@like+1
  end

  def create
  	@post=Post.find(params[:post_id])
  	@like=@post.like.build(params[:text])
  	@like.save

  	redirect_to @post
  end

  private
  def like_params
    params.require(:like).permit(:like, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
 
def index
    @buscado = params[:buscado]
    @posts = Post.where(:title => @buscado)

    @posts = Post.all
    @posts=@posts.reverse

end

  def menu
    @posts = Post.all
  end

  # GET /posts/1
  def show
   @post = Post.find(params[:id])
   respond_to do |format|
      format.html #show,html,erb
      format.xml {render :xml=>@post}
   end
  end

  def show1
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post creado.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post Actualizado.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post Eliminado' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/new.html.erb
<h1>Nuevo Comentario</h1>

<%= form_for(@post.comment.build) do |f| %>
  <form>
  <p><%= f.text_area :text %></p><br>
  <input type="submit" value="Añadir Comentario">
  </form>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/likes/created.html.erb
<h1>Likes#created</h1>
<p>Find me in app/views/likes/created.html.erb</p>

app/views/posts/edit.html.erb
<h1>Editar post</h1>

<% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
 <% end %>

<%= form_for(@post) do |f| %>
  <form>
	Titulo del Post:
	<br> 
	<input type="text" name="post[title]" value="<%= @post.title%>">
	<br>
	<p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
    </p> 	
	<br>
	<input type="submit" value="Editar Post">

  </form>
  
  <% end %>

 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Administrar Posts</h1>

<form>
 <input name="buscado" <%= @buscado %> >
 <button type="submit">Buscar</button>
</form>


<%= link_to "Nuevo post",new_post_path %><br>
<%= link_to "Ir Menu","/menu" %>
<h2>Lista de Posts</h2>


<% @posts.each do |post|%>
  <h3><%= link_to post.title, post %></h3>
  <p><%= post.text %></p>
  <h5>Fecha de Creacion: <%=  post.created_at.strftime("%b %d, %Y") %> </h5>

  
<% end %>

app/views/posts/menu.html.erb
<h1>Mi blog de Edwin de Posts</h1>

<%= link_to "Ir Administrador", "/posts" %>

<h2>Lista de Posts</h2>
<% @posts.each do |post|%>
  <h3><%= link_to post.title,post   %></h3>
  <p><%= post.text %></p>
  <h5>Fecha de Creacion: <%=  post.created_at.strftime("%b %d, %Y") %> </h5>
  <input type="submit" value="Like" >
<% end %>

app/views/posts/new.html.erb
<h1>Nuevo post</h1>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<%= form_for(@post) do |f| %>
  <form>
	Titulo del Post:
	<br> 
	<input type="text" name="post[title]" placeholder="Titulo">
	<br>
	<p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
    </p> 	
	<br>
	<input type="submit" value="Crear Post">

  </form>
  
  <% end %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to "Editar", edit_post_path(@post) %>
<%= link_to "Eliminar",@post,:method=>:delete %> 
<%= link_to "volver", posts_path %>
<br>
<h1> <%= @post.title%> </h1>
<input type="submit" value="Like" >


<p> <%= @post.text%></p>

<%= link_to "Agregar Comentarios", new_comment_path %>

<h3>Comentarios</h3>
<%= @post.comments.each do |comment|%>
<p><%= comment.text%></p>
<h5><%= comment.created_at.strftime("%b %d, %Y") %> </h5>
<%end%>

app/views/posts/show1.html.erb
<h1> <%= @post.title%> </h1>

<p> <%= @post.text%></p>